-- Create the sessions table
CREATE TABLE sessions (
  id TEXT PRIMARY KEY,
  created_by TEXT,
  status TEXT DEFAULT 'waiting',
  preferences JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ,
  partner_id TEXT,
  matched_at TIMESTAMPTZ
);

-- Create the codes table
CREATE TABLE codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT REFERENCES sessions(id) ON DELETE CASCADE NOT NULL,
    content TEXT,
    language TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create the connection_logs table
CREATE TABLE connection_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT REFERENCES sessions(id) ON DELETE CASCADE NOT NULL,
    from_user TEXT NOT NULL,
    to_user TEXT NOT NULL,
    connector TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
